# Numpy
- It is a numerical computing library for python.
- Numpy supports muti-dimensional arrays and matrices.
- It has lot of inbuilt Mathematical Functions.

In [6]:
# installing numpy library
! pip install numpy

In [1]:
# importing numpy as np
import numpy as np

# Why Numpy
- performs fast operations (because of vectorization)
- numpy arrays can be treated as vectors and matrices from linear algebra

In [10]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [14]:
# % => for magic function, timeit => to calculate time taken
%timeit [i**2 for i in lst]

1.73 µs ± 53.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
# numpy array are fast
arr = np.array(lst)

In [16]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
%timeit arr**2

417 ns ± 0.998 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [18]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [20]:
# if i want to add 10 to each element of this vector
lst + [1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

In [21]:
# Possible in Numpy Array
arr + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Numpy Basics
<b>array</b> : fundamental element in numpy is homogenous array. Numpy arrays can be 1D, 2D, 3D,.... nD.
- Different ways to create numpy array
    1. np.array()
    2. np.arrange()


In [22]:
l = [1,2,3,4,5]

In [23]:
np_array = np.array(l)

In [24]:
print(np_array)

[1 2 3 4 5]


In [25]:
np_array

array([1, 2, 3, 4, 5])

In [26]:
type(np_array)

numpy.ndarray

In [27]:
# type = > numpy.ndarray is general for n dimensional array
# to check dimension, there is property called ndim.
np_array.ndim

1

In [29]:
# shape tells => no. of elements and dimension (important property)
np_array.shape

(5,)

<b> Another way of Creating Array </b>

In [31]:
new_arr = np.arange(1,11)
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
new_arr = np.arange(1,11,3)
new_arr

array([ 1,  4,  7, 10])

In [33]:
lst_2d = [[1,2,3],[4,5,6],[7,8,9]]

In [34]:
arr_2d = np.array(lst_2d)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr_2d.ndim

2

In [37]:
# (rows,column)
arr_2d.shape

(3, 3)

# Special Arrays in Numpy
1. zeros()
2. ones()
3. diag()
4. identity()

In [41]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [43]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [45]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Indexing In Array

In [9]:
# for generating random number
np.random.randint(10,20)

16

In [10]:
new_arr = np.random.randint(0,10,(3,3))

In [11]:
new_arr

array([[3, 6, 3],
       [8, 4, 5],
       [8, 6, 3]])

In [12]:
# first row
new_arr[0]

array([3, 6, 3])

In [13]:
# second row
new_arr[1]

array([8, 4, 5])

In [14]:
# last row
new_arr[-1]

array([8, 6, 3])

In [15]:
# first element
new_arr[0, 0]

3

In [16]:
# second last element
new_arr[2, 1]

6

<h3>Array Slicing </h3>

In [21]:
new_arr = np.random.randint(0, 10, (5,5))

In [22]:
new_arr

array([[0, 5, 0, 6, 2],
       [6, 5, 5, 9, 7],
       [0, 5, 8, 9, 7],
       [1, 1, 1, 9, 7],
       [6, 9, 2, 6, 9]])

In [23]:
# syntax => arr[start row index : end row index + 1, start column index : end column index + 1]
new_arr[1:4,1:4]

array([[5, 5, 9],
       [5, 8, 9],
       [1, 1, 9]])

In [31]:
# fourth column 
# same as new_arr[0:5,3:4]
new_arr[:,3]

array([6, 9, 9, 9, 6])

<h3>Masking</h3>

In [3]:
new_arr = np.random.randint(0, 10, (5,5))

In [4]:
new_arr

array([[2, 6, 3, 3, 3],
       [7, 2, 3, 5, 4],
       [4, 1, 8, 5, 5],
       [8, 5, 7, 2, 8],
       [9, 1, 4, 6, 8]])

In [5]:
mask = new_arr > 5

In [6]:
mask

array([[False,  True, False, False, False],
       [ True, False, False, False, False],
       [False, False,  True, False, False],
       [ True, False,  True, False,  True],
       [ True, False, False,  True,  True]])

In [7]:
np.sum(mask)

9

In [8]:
# all the elements greater than 5
new_arr[mask]

array([6, 7, 8, 8, 7, 8, 9, 6, 8])

In [9]:
new_arr

array([[2, 6, 3, 3, 3],
       [7, 2, 3, 5, 4],
       [4, 1, 8, 5, 5],
       [8, 5, 7, 2, 8],
       [9, 1, 4, 6, 8]])

In [10]:
# assign one value to array
new_arr[0,0] = 0

In [11]:
new_arr

array([[0, 6, 3, 3, 3],
       [7, 2, 3, 5, 4],
       [4, 1, 8, 5, 5],
       [8, 5, 7, 2, 8],
       [9, 1, 4, 6, 8]])

In [12]:
# assign multiple values
new_arr[2:,2:] = 27

In [13]:
new_arr

array([[ 0,  6,  3,  3,  3],
       [ 7,  2,  3,  5,  4],
       [ 4,  1, 27, 27, 27],
       [ 8,  5, 27, 27, 27],
       [ 9,  1, 27, 27, 27]])

# Basic Operations In Arrays

In [14]:
a = np.array([10,20,30,40,50])
b = np.arange(1,6)

In [15]:
a

array([10, 20, 30, 40, 50])

In [16]:
b

array([1, 2, 3, 4, 5])

In [17]:
a + b

array([11, 22, 33, 44, 55])

In [18]:
a - b

array([ 9, 18, 27, 36, 45])

In [19]:
a * b

array([ 10,  40,  90, 160, 250])

In [20]:
b**2

array([ 1,  4,  9, 16, 25])

In [21]:
a**3

array([  1000,   8000,  27000,  64000, 125000])

In [22]:
# Masking
a > 23

array([False, False,  True,  True,  True])

In [24]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [25]:
np.sin(b)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

# Matrix Product

In [26]:
A = np.random.randint(0, 5, (3,4))
B = np.random.randint(0, 5, (4,2))

In [27]:
A

array([[2, 0, 2, 4],
       [2, 2, 3, 1],
       [0, 1, 2, 4]])

In [28]:
B

array([[1, 3],
       [3, 2],
       [2, 2],
       [0, 0]])

In [32]:
# Dot Product
np.dot(A,B)

array([[ 6, 10],
       [14, 16],
       [ 7,  6]])

<h3>More Operations On Array </h3>

In [2]:
A = np.arange(0,24)

In [3]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [4]:
# 1-D shape
A.shape

(24,)

In [6]:
A = A.reshape(6,4)

In [7]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
A.shape

(6, 4)

In [9]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [10]:
np.sum(A)

276

In [11]:
np.max(A)

23

In [12]:
np.min(A)

0

In [13]:
# Standard Deviation
np.std(A)

6.922186552431729

In [14]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
# sum across row
np.sum(A, axis = 0)

array([60, 66, 72, 78])

In [16]:
# sum across column
np.sum(A, axis = 1)

array([ 6, 22, 38, 54, 70, 86])

In [18]:
np.mean(A, axis = 1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

# Shape Manipulation

In [19]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
# To flatten array i.e 1-D array
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
A.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [23]:
# Transpose Rows become Columns and Columns become Rows
A.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [24]:
np.transpose(A)

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

<h2>Stacking Of Arrays</h2> Vstack - Hstack

In [25]:
a = np.random.randint(0,10 ,(2,2))
b = np.random.randint(0,10 ,(2,2))

In [26]:
a

array([[2, 1],
       [3, 6]])

In [27]:
b

array([[3, 6],
       [1, 1]])

In [28]:
# Horizontal 
np.hstack((a,b))

array([[2, 1, 3, 6],
       [3, 6, 1, 1]])

In [29]:
# Vertical
np.vstack((a,b))

array([[2, 1],
       [3, 6],
       [3, 6],
       [1, 1]])

# Broadcasting
- First Rule Of NumPy - 2 Arrays can perform operations only when they have same shapes.
- Broadcasting let two arrays of different shapes to do some operations.
    - A small array will repeat itself and convert to same shape as of another array.

In [38]:
A = np.random.randint(0, 10, (3,3))
a = np.array([[1, 2, 3]])

In [39]:
A

array([[8, 5, 2],
       [5, 7, 8],
       [5, 4, 6]])

In [40]:
a

array([[1, 2, 3]])

In [41]:
print(A.shape, a.shape)

(3, 3) (1, 3)


In [42]:
A + a

array([[ 9,  7,  5],
       [ 6,  9, 11],
       [ 6,  6,  9]])

In [43]:
a.T

array([[1],
       [2],
       [3]])

In [44]:
A + a.T

array([[ 9,  6,  3],
       [ 7,  9, 10],
       [ 8,  7,  9]])

In [45]:
A

array([[8, 5, 2],
       [5, 7, 8],
       [5, 4, 6]])

In [47]:
# Add 4 to each Element
A + 4

array([[12,  9,  6],
       [ 9, 11, 12],
       [ 9,  8, 10]])

# Vectorization
- Performing Operations Directly on Array

In [49]:
p1 = np.array([1,2])
p2 = np.array([5,5])

In [50]:
s = 0
for i in range(2):
    s += (p2[i] - p1[i])**2
    
print(s**0.5)    

5.0


In [51]:
# Efficient because of vectorization
np.sqrt(np.sum((p2-p1)**2))

5.0